# Generated by Django 2.0.3 on 2018-04-05 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Journal Title')),
                ('content', models.TextField()),
                ('published_on', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
